name: mmgoods
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.10+1

  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_slidable: ^2.0.0
  flutter_local_notifications: ^11.0.1
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.5.4
  pull_to_refresh: ^2.0.0
  lottie: ^1.4.3
  flutter_share: ^2.0.0
  card_swiper: ^2.0.4
  swipe_deck: ^1.1.0
  barcode: ^2.2.3
  flutter_svg: ^1.1.5
  table_calendar: ^3.0.7
  moment_dart: ^0.10.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - lib/assets/lottie/
    - lib/assets/images/